apiVersion: v1
kind: Service
metadata:
  name: ezfastfood-api-service
  namespace: ezfastfood
spec:
  type: NodePort
  selector:
    app: ezfastfood
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
