apiVersion: apps/v1
kind: Deployment
metadata:
  name: ez-fast-food-deployment
  namespace: ez-fast-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ez-fast-food
  template:
    metadata:
      labels:
        app: ez-fast-food
    spec:
      containers:
      - name: ez-fast-food-container
        image: dasilvathaynara/ez-fast-food-api:latest
        imagePullPolicy: IfNotPresent # Add this line
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms100m -Xmx512m -XX:+UseParallelGC"  #JVM
        envFrom:
        - configMapRef:
            name: ez-fast-food-configmap-app   # Reference the created ConfigMap
        resources:
          requests:
            cpu: "250m" ## a solucao requer mais cpu no momento de inicializacao. Este e o minimo saudavél para que os containers subam sem erro.
            memory: "150Mi"
          limits:
            cpu: "350m"
            memory: "750Mi"
        readinessProbe:
            httpGet:
                path: /actuator/health 
                port: 8080
            initialDelaySeconds: 35   # tempo definido de acordo com o tempo de inicializacao da API (~30 a ~40)
            periodSeconds: 10
            failureThreshold: 3