apiVersion: v1
kind: Secret
metadata:
  name: ezfastfood-secret
  namespace: ezfastfood
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM= 
  POSTGRES_USER: cG9zdGdyZXM=    
  POSTGRES_PASSWORD: cG9zdGdyZXM=