apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ez-fast-food-hpa
  namespace: ez-fast-food
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ez-fast-food-deployment  # Deployment to scale
  minReplicas: 1                   # Minimum number of pods
  maxReplicas: 4                   # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75   # Reduced target CPU utilization for faster scaling