apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ez-fast-food-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ez-fast-food-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
