apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ez-fast-food
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007  # You can specify a static port or let Kubernetes assign one.