apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ezfastfood-postgres-pvc
  namespace: ezfastfood
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi