apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ez-fast-food
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      #nodePort: 3007