apiVersion: v1
kind: PersistentVolume
metadata:
  name: ezfastfood-postgres-pv  # Name of the PV
  namespace: ezfastfood
spec:
  capacity:
    storage: 2Gi  # Define the storage size
  accessModes:
    - ReadWriteOnce  # Define the access mode
  persistentVolumeReclaimPolicy: Retain  # Define the reclaim policy
  storageClassName: hostpath # Ensure this matches the PVC
  #hostPath:  # This is using local storage; replace with a different storage backend if needed
    #path: /mnt/data  # Local directory on the node (not recommended for production) ----> ideal eh trocar para apontar para bd em nuvem
